CREATE TABLE dbo.users (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  username NVARCHAR(100) NOT NULL, email NVARCHAR(254) NOT NULL, password_hash NVARCHAR(255) NOT NULL,
  mfa_enabled BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_users_username UNIQUE (username), CONSTRAINT UQ_users_email UNIQUE (email)
);
CREATE TABLE dbo.sessions (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, user_id UNIQUEIDENTIFIER NOT NULL, token_hash VARCHAR(64) NOT NULL,
  expires_at DATETIME2 NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_sessions_user FOREIGN KEY (user_id) REFERENCES dbo.users(id) ON DELETE CASCADE, CONSTRAINT UQ_sessions_token_hash UNIQUE (token_hash)
);
CREATE INDEX IX_sessions_expiry ON dbo.sessions(expires_at);
